### ISSUE TITLE
Problem installing on some Safari versions?

### ISSUE THREAD

**Issue by cliffrowley** [cliffrowley/makesafaridrumpf#1]
Tried installing this on my wife's Mac and despite the install process seemingly working and being presented with the "Trust" button, clicking it has no effect and the extension is not installed.

This _may_ be related to the fact that I had to update my El Capitan to the latest beta in order to work around a Safari extension builder bug that prevented it from seeing my private key in order to sign the release.

Will investigate.  In the meantime, if anyone happens to read this and is having the same problem, let me know thanks.

**Comment by Johnny-8** [comment]
### I've just run into the **same** issue.
Both iMacs running 10.12.5 (16F73) and Safari 10.1.1 (12603.2.4)
**iMac 13,2** - makesafaridrumpf installs and works.
**iMac 10,1** - Install process appears to work but extension is not installed.

**Comment by cliffrowley** [comment]
I never really worked out what the problem was on earlier Safari versions unfortunately, but thanks for letting me know - at least I know it wasn't just me ;-)
